ProjectX.Web2/Areas/Definitions/Controllers/ItemController.cs
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using ProjectX.Service;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectX.Web.Utility;
using ProjectX.Web.Areas.Definitions.Models;
using System.Threading.Tasks;
using System.Web.Http;
using ProjectX.Entities.Models;
using Repository.Pattern.Infrastructure;

namespace ProjectX.Web.Areas.Definitions.Controllers
{
    public class ItemController : Controller, IDisposable
    {
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly IItemService _itemService;

        public ItemController(IUnitOfWorkAsync unitOfWork, IItemService itemService)
        {
            _unitOfWorkAsync = unitOfWork;
            _itemService = itemService;
        }

        // GET: Definitions/Article
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateUpdate(string id) 
        {
            if (string.IsNullOrEmpty(id))
                return View(new ItemModel());

            ItemModel model = Mappings.ToModel(_itemService.Queryable().Where(i => i.ItemFullCode == id).FirstOrDefault());
            model.isEditMode = true;

            return View(model);
        }

        #region Grid Methods

        //public ActionResult Item_Read([DataSourceRequest] DataSourceRequest request)
        //{
        //    return Json(_itemService.Queryable().OrderBy(i => i.ItemFullCode).ToDataSourceResult(request));
        //}

        #endregion

        #region Crud Methods

        //public async Task<ActionResult> Save([FromBody] ItemModel model)
        //{
        //    if (!ModelState.IsValid)
        //        return View(model);

        //    Item item = Mappings.ToEntity(model);
        //    item.ObjectState = ObjectState.Modified;
        //    _itemService.Update(item);

        //    try
        //    {
        //        await _unitOfWorkAsync.SaveChangesAsync();
        //    }
        //    catch (Exception ex) 
        //    {
        //        if (!ItemExists(model.ItemFullCode))
        //            return NotFound();

        //        throw;
        //    }
        //}

        #endregion

        #region Private Methods

        private bool ItemExists(string key)
        {
            return _itemService.Query(i => i.ItemFullCode == key).Select().Any();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWorkAsync.Dispose();
            }
            base.Dispose(disposing);
        }

        #endregion
    }
}

ProjectX.Web2/Areas/Definitions/Controllers/MainCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectX.Web.Areas.Definitions.Controllers
{
    public class MainCategoryController : Controller
    {
        // GET: Definitions/MainCategory
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjectX.Web2/Areas/Definitions/Controllers/SubInvController.cs
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using ProjectX.Service;
using ProjectX.Web.Utility;
using Repository.Pattern.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectX.Web.Areas.Definitions.Models;
using ProjectX.Entities.Models;
using Repository.Pattern.Infrastructure;
using System.Data.Entity.Infrastructure;

namespace ProjectX.Web.Areas.Definitions.Controllers
{
    public class SubInvController : Controller, IDisposable
    {
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly ISubInventoryService _subInventoryService;

        public SubInvController(
                IUnitOfWorkAsync unitOfWorkAsync,
                ISubInventoryService subInventoryService)
        {
            _unitOfWorkAsync = unitOfWorkAsync;
            _subInventoryService = subInventoryService;
        }

        #region Page Methods

        //
        // GET: /Definitions/SubInv/
        public ActionResult Index()
        {            
            return View();
        }

        //public JsonResult GetSubInv()
        //{
        //    return Json(_subInventoryService.Queryable().OrderBy(s => s.SubInvCode), JsonRequestBehavior.AllowGet);
        //}

        #endregion

        #region Grid Methods

        public ActionResult SubInv_Read([DataSourceRequest] DataSourceRequest request)
        {
            //Mappings.ToModel(_subInventoryService.Queryable().OrderBy(s => s.SubInvCode));
            return Json(_subInventoryService.Queryable().OrderBy(s => s.SubInvCode).ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SubInv_Create([DataSourceRequest] DataSourceRequest request, SubInventoryModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                SubInventory subinv = Mappings.ToEntity(model);
                subinv.ObjectState = ObjectState.Added;
                subinv.CreatedBy = subinv.ModifiedBy = "I-ALI";
                subinv.CreatedDate = subinv.ModifiedDate = DateTime.Now;

                _subInventoryService.Insert(subinv);

                try
                {
                     _unitOfWorkAsync.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(subinv.SubInvCode))
                        throw new Exception("Item already exists.");

                    throw;
                }
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SubInv_Update([DataSourceRequest] DataSourceRequest request, SubInventoryModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                //productService.Update(model);
                SubInventory subinv = Mappings.ToEntity(model);
                subinv.ObjectState = ObjectState.Modified;
                subinv.ModifiedBy = "I-ALI";
                subinv.ModifiedDate = DateTime.Now;

                _subInventoryService.Update(subinv);

                try
                {
                    _unitOfWorkAsync.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(model.SubInvCode))
                        throw new Exception("Item does not exist.");

                    throw;
                }
            }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SubInv_Destroy([DataSourceRequest] DataSourceRequest request, SubInventoryModel model)
        {
            if (model != null)
            {
                //productService.Destroy(model);
                SubInventory subinv = _subInventoryService.Find(model.SubInvCode);

                if (subinv == null)
                    throw new Exception("Item does not exist.");

                subinv.ObjectState = ObjectState.Deleted;

                _subInventoryService.Delete(subinv);

                _unitOfWorkAsync.SaveChanges();
           }

            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        #endregion

        #region Private Methods

        private bool ItemExists(string key)
        {
            return _subInventoryService.Query(i => i.SubInvCode == key).Select().Any();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _unitOfWorkAsync.Dispose();
            }
            base.Dispose(disposing);
        }

        #endregion
    }
}

ProjectX.Web2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/vendors/css/styles")
    @Styles.Render("~/Content/themes/css")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendo/2015.1.429/css")
    @Scripts.Render("~/bundles/scripts")
    <!--[if lt IE 9]>
        <script src="../assets/js/ie8-responsive-file-warning.js"></script>
    <![endif]-->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                @Html.Partial("_LeftNav")
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="~/images/img.jpg" alt="">@User.Identity.Name
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"> Profile</a></li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="badge bg-red pull-right">50%</span>
                                            <span>Settings</span>
                                        </a>
                                    </li>
                                    <li><a href="javascript:;">Help</a></li>
                                    <li><a href="javascript:document.getElementById('logout_form').submit()"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>
                            <li role="presentation" class="dropdown">
                                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-envelope-o"></i>
                                    <span class="badge bg-green">6</span>
                                </a>
                                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a>
                                            <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                            <span>
                                                <span>John Smith</span>
                                                <span class="time">3 mins ago</span>
                                            </span>
                                            <span class="message">
                                                Film festivals used to be do-or-die moments for movie makers. They were where...
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="text-center">
                                            <a>
                                                <strong>See All Alerts</strong>
                                                <i class="fa fa-angle-right"></i>
                                            </a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            @RenderBody()
            <!-- /page content -->
            <!-- logout form -->
            @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logout_form", @style = "display:hidden" }))
            {
                @Html.AntiForgeryToken()
            }
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>   
    @Scripts.Render("~/bundles/theme")
    @Scripts.Render("~/bundles/kendo")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjectX.Web2/Views/Shared/_LeftNav.cshtml
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
    </div>
    <div class="clearfix"></div>
    <!-- menu profile quick info -->
    <div class="profile clearfix">
        <div class="profile_pic">
            <img src="~/images/img.jpg" alt="..." class="img-circle profile_img">
        </div>
        <div class="profile_info">
            <span>Welcome,</span>
            <h2>@User.Identity.Name</h2>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- /menu profile quick info -->
    <br />
    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
                <li>
                    <a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="index.html">Dashboard</a></li>
                        <li><a href="index2.html">Dashboard2</a></li>
                        <li><a href="index3.html">Dashboard3</a></li>
                    </ul>
                </li>
                <li>
                    <a><i class="fa fa-table"></i> Definitions <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li>@Html.ActionLink("Sub Inventory", "SubInv", "Definitions", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Main Category", "MainCategory", "Definitions", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Sub Category", "SubCategory", "Definitions", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Article", "Item", "Definitions", new { area = "" }, null)</li>
                    </ul>
                </li>
                <li>
                    <a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="form.html">General Form</a></li>
                        <li><a href="form_advanced.html">Advanced Components</a></li>
                        <li><a href="form_validation.html">Form Validation</a></li>
                        <li><a href="form_wizards.html">Form Wizard</a></li>
                        <li><a href="form_upload.html">Form Upload</a></li>
                        <li><a href="form_buttons.html">Form Buttons</a></li>
                    </ul>
                </li>
                <li>
                    <a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="general_elements.html">General Elements</a></li>
                        <li><a href="media_gallery.html">Media Gallery</a></li>
                        <li><a href="typography.html">Typography</a></li>
                        <li><a href="icons.html">Icons</a></li>
                        <li><a href="glyphicons.html">Glyphicons</a></li>
                        <li><a href="widgets.html">Widgets</a></li>
                        <li><a href="invoice.html">Invoice</a></li>
                        <li><a href="inbox.html">Inbox</a></li>
                        <li><a href="calendar.html">Calendar</a></li>
                    </ul>
                </li>                
                <li>
                    <a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="chartjs.html">Chart JS</a></li>
                        <li><a href="chartjs2.html">Chart JS2</a></li>
                        <li><a href="morisjs.html">Moris JS</a></li>
                        <li><a href="echarts.html">ECharts</a></li>
                        <li><a href="other_charts.html">Other Charts</a></li>
                    </ul>
                </li>
                <li>
                    <a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                        <li><a href="fixed_footer.html">Fixed Footer</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="menu_section">
            <h3>Live On</h3>
            <ul class="nav side-menu">
                <li>
                    <a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="e_commerce.html">E-commerce</a></li>
                        <li><a href="projects.html">Projects</a></li>
                        <li><a href="project_detail.html">Project Detail</a></li>
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="profile.html">Profile</a></li>
                    </ul>
                </li>
                <li>
                    <a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="page_403.html">403 Error</a></li>
                        <li><a href="page_404.html">404 Error</a></li>
                        <li><a href="page_500.html">500 Error</a></li>
                        <li><a href="plain_page.html">Plain Page</a></li>
                        <li><a href="login.html">Login Page</a></li>
                        <li><a href="pricing_tables.html">Pricing Tables</a></li>
                    </ul>
                </li>
                <li>
                    <a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="#level1_1">Level One</a>
                        <li>
                            <a>Level One<span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li class="sub_menu">
                                    <a href="level2.html">Level Two</a>
                                </li>
                                <li>
                                    <a href="#level2_1">Level Two</a>
                                </li>
                                <li>
                                    <a href="#level2_2">Level Two</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#level1_2">Level One</a>
                        </li>
                    </ul>
                </li>
                <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
            </ul>
        </div>
    </div>
    <!-- /sidebar menu -->
    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout" href="javascript:document.getElementById('logout_form').submit()">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
    </div>
    <!-- /menu footer buttons -->
</div>